PImage img;
PImage ball;
PImage Yeet;
PImage Paddle1;
PImage Paddle2;
int ballXReset = 450;
int ballYReset = 500;
int Paddle1Y;
int Paddle2Y;
int Paddle1Height;
int Paddle2Width = 950;
int Paddle2Height;
int Paddle1Start;
int Paddle2Start;
int Paddle1X = 60;
int Paddle2X = 840;
int ballX;
int ballY;
int ballStartX = 450;
int ballStartY = 500;
int ballXSpeed = 5;
int ballYSpeed = 5;
int [] player = new int [4];
int [] score = {0, 0};
