PImage img;
PImage ball;
PImage Yeet;
PImage Paddle1;
PImage Paddle2;

int Paddle1Position;
int ballXReset = 450;
int ballYReset = 500;
float Paddle2Position;
float ballPosition;
int Paddle1Y;
int Paddle2Y;
int Paddle1Height;
int Paddle1Start;
int Paddle2Start;
int Paddle1X = 60;
int Paddle2X = 840;
int ballX;
int ballY;
int ballstartX;
int ballstartY;
float ballXmove = 5.0;
float ballYmove = 5.0;
int speedX = 2;
int speedY = 2;
int directionX = 1;
int directionY = 1;
