PImage img;
PImage ball;
PImage Yeet;
PImage Paddle1;
PImage Paddle2;
Boolean ballArea;
float Paddle1Position;
float Paddle2Position;
float ballPosition;
float Paddle1Y;
float Paddle2Y;
int Paddle1Start;
int Paddle2Start;
int Paddle1X = 60;
int Paddle2X = 840;
int ballX;
int ballY;
int ballstartX;
int ballstartY;
float ballXmove = 1.0;
float ballYmove = 1.0;
int speedX = 2;
int speedY = 2;
int directionX = 1;
int directionY = 1;
